### ISSUE TITLE
[Bug] Deleter returns "Ended because API returned an empty page." instead of deleting messages

### ISSUE THREAD

**Issue by RaphiM** [victornpb/deleteDiscordMessages#57] opened 2020-04-02 22:42 UTC
The deleter deleter doesnt work, it finds the 2000 odd messages in the dm's but instead of deleting gives the reason "Ended because API returned an empty page." for not deleting any messages.

**Comment by mhannigan** [comment] 2020-04-03 00:45
I am having the same problem with a new twist.  It will delete some messages - sometimes 10, 20, 100, etc... then it gives me this message "Ended because API returned an empty page" at the end of each run.  Finally (when there are still a few thousand messages left), it will only show this message and delete nothing.  It doesn't matter how long I wait - sometimes I will get the popup that says I have 1 message, sometimes no popup.

**Comment by bobfranklin** [comment] 2020-05-26 17:32
I have this same issue. it seems to fail when it doesnt find a message on a page but recognizes there are many more messages in history

Delete delay: 100ms, Search delay: 100ms	Last Ping: 203ms, Average Ping: 304ms
Estimated time remaining: 0h 17m 38s
Ended because API returned an empty page.
Ended at 5/26/2020, 10:31:50 AM! Total time: 0h 0m 32s
Delete delay: 100ms, Search delay: 100ms	Last Ping: 203ms, Average Ping: 304ms
Rate Limited: 0 times. Total time throttled: 0h 0m 0s.
Deleted 55 messages, 0 failed.

**Comment by victornpb** [comment] 2020-06-04 00:38
duplicate of #55

**Closed** 2020-06-04 00:38 UTC
