### ISSUE TITLE
[BUG] "Ended because API returned an empty page" "Deleted 0 messagess, 0 failed" even though there are 144k more messages to delete

### ISSUE THREAD

**Issue by throwaway369** [victornpb/deleteDiscordMessages#137] opened 2020-10-28 13:55 UTC
**Describe the bug**
title, this happens on both my desktop computer and laptop.
edit: i suspect this might be because the first search page only yields "started a call" messages, but what do i know.
**EDIT: workaround by setting the "before" date range to not include the "started a call" messages.**
**To Reproduce**
start from default settings, click the 3 get buttons, check include pinned, click start.

**Screenshots / Logs**
![image](https://user-images.githubusercontent.com/73597064/97445685-71489a80-1925-11eb-84e6-81a3d56e86a1.png)

**Affects** (Add an X to items that apply)
- [X] DMs
- [ ] DM Groups
- [ ] Channel
- [ ] Channel (NSFW)
- [ ] Server (All Channels)
- [ ] Other (explain)

**System:**
 - OS: Windows 10
 - Chrome 86.0.4240.111

**Comment by victornpb** [comment] 2020-10-29 21:54
At first glance it seems plausible that an entire page of system messages would make the algorithm think it reached the end. I'll have to take a look at the code tho I can't quite remember of the top of my head

**Comment by victornpb** [comment] 2020-10-29 22:09
Duplicate of #122

**Closed** 2020-10-29 22:09 UTC
Labels: bug, duplicate
