### ISSUE TITLE
The call log blocks the code from continuing to wipe everything.

### ISSUE THREAD

**Issue by DanTGT** [victornpb/deleteDiscordMessages#133] opened 2020-10-14 09:42 UTC
The program runs into an error when there are calls logged since they cannot be deleted every message above them is still there and the bot pulls back the end process command for "Ended because API returned an empty page" Please get back to me soon with a fix if possible

**Comment by OstrichRider** [comment] 2020-10-14 19:51
Yep, same thing just happened to me. Very concerning I have messages I don't want viewed but I can't delete them.

**Comment by OstrichRider** [comment] 2020-10-14 19:52
Oh I just realized you can use the "range" feature as a work around until this bug gets fixed

**Comment by chungdublo** [comment] 2020-10-15 14:14
#112

**Comment by victornpb** [comment] 2020-10-29 22:10
Duplicate of #122

**Closed** 2020-10-29 22:10 UTC
Labels: duplicate
