### ISSUE TITLE
Deletion stops after 26 messages in DM

### ISSUE THREAD

**Issue by Deevits** [victornpb/deleteDiscordMessages#23] opened 2019-11-20 13:13 UTC
Hi! First of all, thanks for all your effort of coding this thing! 
For some reason though, every time I try to delete the messages in DM it stops after 26 messages: 

0.12% (26/22548)	Deleting ID:641395138689630220 User#9999 (5-11-2019 22:55:17): Wat?	
Searching next messages in 100ms...	
Total messages found: 22548	(Messages in current page: 0, Author: 0, System: 0)	offset: 0
Delete delay: 365ms, Search delay: 100ms	Last Ping: 253ms, Average Ping: 198ms
Estimated time remaining: 3h 33m 18s
Ended because API returned an empty page.
Ended at 20-11-2019 13:58:47! Total time: 0h 0m 18s
Delete delay: 365ms, Search delay: 100ms	Last Ping: 253ms, Average Ping: 198ms
Rate Limited: 1 times. Total time throttled: 0h 0m 0s.
Deleted 26 messages, 0 failed.

Am I doing something wrong here? Using Chrome.

**Comment by charlie721628** [comment] 2019-11-20 16:08
I am also encountering this issue, I don't think it's on your end. I tried both Chrome and Firefox to no avail.

**Comment by tuokri** [comment] 2019-11-20 23:26
Confirmed

**Comment by bparker06** [comment] 2019-11-21 18:56
Same here, this just started happening in the last week or so I believe. It will find >100 messages and then delete only a few dozen. Repeated attempts find no existing messages when they're obviously still there.

**Comment by tuokri** [comment] 2019-11-22 06:00
A few things I noticed:

- Repeating the deletion attempt after waiting an extended period of time makes it work again (but only up to 26 messages). I didn't measure the time but it ranged from several minutes to an hour.
- Specifying the message ID range manually makes the deletion work again, but yet again only up to 26 messages.

**Comment by purtechnikon** [comment] 2019-11-23 19:06
same problem here

**Comment by larryqiann** [comment] 2019-11-23 20:27
I'm having the same issue. After playing around it looks like the Discord search UI has the same issue and you have to click the "next" button a few times.

**Comment by larryqiann** [comment] 2019-11-23 21:21
After some testing I was able to hack it into working. Using inspect element it looks like Discord uses different URLs for searching and for actually deleting. 

I made these changes in the code to get it working in a server:

Under the 'recurse' function:
`const baseURL = `https://discordapp.com/api/v6/guilds/58***64/messages/`;
            const baseURLD = `https://discordapp.com/api/v6/channels/58***76/messages/`;`

However, using this method, we need to implement filtering by channel in search, because otherwise it will find a lot of messages in other channels and try to delete them resulting in 404s. Furthermore, the values are hardcoded right now and need to be updated each time. 

Another issue is that I needed to modify the last else block to update the offset to 25*iterations, and then recurse again. This causes some bugs where the script doesn't stop running and just loops so I need to watch it while it is running.

**Comment by jumphil** [comment] 2019-11-26 08:35
I'm having the exact same problem, a fix would be much appreciated

**Comment by victornpb** [comment] 2019-12-01 20:33
> After some testing I was able to hack it into working. Using inspect element it looks like Discord uses different URLs for searching and for actually deleting.
> 
> I made these changes in the code to get it working in a server:
> 
> Under the 'recurse' function:
> `const baseURL = `[https://discordapp.com/api/v6/guilds/58***64/messages/`](https://discordapp.com/api/v6/guilds/58***64/messages/%60);
> const baseURLD = `https://discordapp.com/api/v6/channels/58***76/messages/`;`
> 
> However, using this method, we need to implement filtering by channel in search, because otherwise it will find a lot of messages in other channels and try to delete them resulting in 404s. Furthermore, the values are hardcoded right now and need to be updated each time.
> 
> Another issue is that I needed to modify the last else block to update the offset to 25*iterations, and then recurse again. This causes some bugs where the script doesn't stop running and just loops so I need to watch it while it is running. Moreover, the reliability is still pretty poor.

@larryqiann Thank you for this insight. I wasn't aware of this new endpoint, I'm working on it.
I'm closing this issue as duplicate of #24

**Closed by victornpb** 2019-12-01 20:33 UTC
Labels: bug
