### ISSUE TITLE
[Question] New Discord rate limiting

### ISSUE THREAD

**Issue by aboose-aboose-aboose** [victornpb/deleteDiscordMessages#128] opened 2020-10-07 18:55 UTC
I have been an avid user of this script for a while now. It's great and does everything I need.

I ran it for the first time in a while today and found I am being rate limited to at minimum 6000ms per deletion by Discord.

Is this a new problem? It practically breaks the script as it takes hours to delete a few hundred messages.

**Comment by whalehub** [comment] 2020-10-09 04:39
Duplicate of #118.

**Closed** 2020-10-28 04:10 UTC
