### ISSUE TITLE
adding a feature allowes to delete messages only but not files and and links??

### ISSUE THREAD

**Issue by ShadowSocks12** [victornpb/deleteDiscordMessages#66] opened 2020-05-17 17:08 UTC
Hi
I see that I can only:
-Delete everything.
-Delete links only or files only or files and links together only.
Note: I don't know what does "include NSFW" do.
How about you add a feature that allows to delete messages that doesn't contain files and links? Please.

**Comment by JustinBayette** [comment] 2020-05-17 18:26
That's the default option. As long as you don't select anything else it should delete messages without files or images.

**Comment by ShadowSocks12** [comment] 2020-05-17 19:06
ok, another question, can I make that script work without using discord on browser? I mean can I use it on discord application?
I could only show console using ctrl+shift+i   , and then i entered the script, but no pop-up appeared,

**Comment by victornpb** [comment] 2020-06-04 00:51
Duplicate of #64

**Closed by victornpb** 2020-06-04 00:51 UTC
Labels: duplicate, wontfix
