### ISSUE TITLE
[Question] Ended because API returned an empty page.

### ISSUE THREAD

**Issue by piiinktape** [victornpb/deleteDiscordMessages#112] opened 2020-08-27 00:26 UTC
Was working initially, but eventually got error. The channel is an @me thread (DM messages).

![image](https://user-images.githubusercontent.com/70300086/91369611-38cbf980-e7da-11ea-8e66-73d7ab38e98a.png)

**Comment by BleedingOptimism** [comment] 2020-08-27 08:04
I haven't looked at any of the code, but I believe the script continues to check backwards until it discovers that there's no more messages (empty page). I don't think it is an error and is actually more like a warning, but that the program is actually functioning as intended when you see it.

**Comment by BleedingOptimism** [comment] 2020-08-27 08:09
If the script isn't deleting any messages, I think you have a different kind of problem as it said that message every time I used it previously.
Duplicate of #110

**Comment by piiinktape** [comment] 2020-08-29 00:52
I had deleted over 20k messages (about half) and then turned off my PC for the night. Next morning it returned the error and still doesn't work.

**Comment by chungdublo** [comment] 2020-09-03 21:33
I was also experiencing this issue. I had about 22k messages to delete and got it down to 8k after running it for about a day. Then the API started returning an empty page.

I was able to fix this by first finding my message the script had stopped on and copying its ID. Then I set it to delete all messages before that one. It worked normally again after that. I was able to find it using discord's search features, to look for messages by me.

I think what might have been happening was that there were just so many messages between the present and where it stopped deleting messages that it was not able to go that far back and find my messages anymore. I had already deleted like 3 years of messages so it was trying to read messages back from 2020 to find where it had left off, which was in like early 2017.

I hope this makes sense and helps someone experiencing the same issue.

**Comment by victornpb** [comment] 2020-09-15 16:54
From what you describing Discord API is putting a soft limit to how back the search goes into the past. If that's the case I can add an initial date like 2015 as a default.

The thing is, it is very hard to test for those edge cases, because I can't generate messages in the past in order to test.

**Comment by Bonista** [comment] 2020-09-28 14:51
@victornpb I might be wrong, but I think this issue is caused by if there is any calls being initiated.
For example, I have like 8 pages of "X  started a call that lasted 6 minutes.", so to find actual messages, the thing has to skip a lot of pages.

https://github.com/victornpb/deleteDiscordMessages/blob/536855e1b6a2d03cf1ef2a185ba1172c8ae57228/deleteDiscordMessages.js This works for me.

**Comment by piiinktape** [comment] 2020-09-28 15:22
> @victornpb I might be wrong, but I think this issue is caused by if there is any calls being initiated.
> For example, I have like 8 pages of "X started a call that lasted 6 minutes.", so to find actual messages, the thing has to skip a lot of pages.
> 
> https://github.com/victornpb/deleteDiscordMessages/blob/536855e1b6a2d03cf1ef2a185ba1172c8ae57228/deleteDiscordMessages.js This works for me.

I'm not sure if that was the issue; @chungdublo 's fix worked best for me to finish deleting all messages.

**Comment by Balls0fSteel** [comment] 2020-10-15 15:52
tbh lately I've been just editing the script by hand after install. I put 1000ms and then it's smooth.

**Comment by victornpb** [comment] 2020-10-29 22:09
Duplicate of #122

**Closed** 2020-10-29 22:09 UTC
Labels: bug
