### ISSUE TITLE
[Question] getting error, Error searching messages, API responded with status 404! 	{"message":"404: Not Found","code":0}

### ISSUE THREAD

**Issue by woinbo** [victornpb/deleteDiscordMessages#82] opened 2020-06-14 04:29 UTC
Error searching messages, API responded with status 404!
	{"message":"404: Not Found","code":0}

plz tell how to solve

**Comment by victornpb** [comment] 2020-06-14 22:12
duplicate of #81

**Closed by victornpb** 2020-06-14 22:12 UTC
Labels: duplicate
